### ISSUE TITLE
todo-management-tool eBook.pdf

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/todo-management-tool#6]
Test von eBook.pdf

Danke für die Mühe und das Tutorial :) Ich finde es gelungen und aufschlussreich, auch wenn ich so meine Probleme hatte.

Vorwort:
Könnte um Docker und npm erweitert da lernt man auch noch ein wenig.

**1:** git clone wird nicht erwähnt

**2:** >_git checkout sign ---> wurde von mir falsch verstanden und ich habe versucht sign auszuchecken xD

**3:** (Seite 5) 
git checkout c01_todo_api_contract
müsste sein
git checkout c01_todo**s**_api_contract

**4:** Practice Time (Seite 6) “go to the folder /api” im branch c01_todos_api_contract gibt es keinen /api ordner

**5:** (Seite 9) npm install muss im /client ordner ausgeführt werden sonst funktioniert es nicht. “go to the folder /client” wird erst nach dem npm install beschrieben.

**6:** (Seite 15 ) Der Code in der grauen Box welche nach dem Text
“Peter was kind enough to add an OpenApi 2.0 generator to the Furo Build flow.”
kommt wurde im Projekt nicht gefunden?!? Was ist das? Ein .furo Beispiel welches nicht im Code-Beispiel drin ist oder ev. nicht auf den Branch 04 bezogen ist?

**7:** (Seite 18)  hat bei mir nicht funktioniert, obwohl ich Envs auf verschiedene Arten definiert habe hat go diese nicht gelesen…
Beispiel nicht unnötig kompliziert machen und direkt in den Code eintragen wäre eine Lösung.

Boot the gRPC Gateway
cd api
GW_SERVER_ADDRESS=localhost:8481
GRPC_SERVER_ADDRESS=localhost:7070 go run ./...
 

**8:** Konnte den Punkt 06 auch nicht machen da ich den gRPC Gateway nicht starten konnte :enttäuscht:
Wurde nicht erwähnt aber ich gehe davon aus dass ich für die Tests die App in Abschnitt 06 wieder hätte starten sollen. :zwinkern:

**Links:**

1. Study Code https://github.com/theNorstroem/todo-management-tool/commit/b9035991096b9cd843a83198b023284bd764b735 was genau war der code der wichtig ist? falscher link oder hab ich es übersehen?
2. (Seite 15) https://editor.swagger.io/# link wird beim Click auf dem Mac als https://editor.swagger.io/%23 geöffnet und zeigt einen 404 Copy-Paste funktioniert jedoch.
3. Study Code (Seite 21) https://github.com/theNorstroem/todo-management-tool/blob/cc9a8d2b9e6dbd1cb0b2f72bd2 a6d4d83e070654/grpc-backend/cmd/internal/todo/todogrpc.go#L31 wird nicht gefunden 404.
4. (Seite 22 ) https://developers.google.com/protocol-buffers/docs/overview#generating wird aus dem PDF mit klick als https://developers.google.com/protocol-buffers/docs/overview%23generating geöffnet 404
5. (Seite 26) https://github.com/theNorstroem/todo-management-tool/blob/2de996a21a7dc0e5e236d66df 295eddddb2cceb2/client/src/create/view-create-todos.js#L140 kann nicht gefunden werden 404
6. Soweit mein Stand vom eBook.pdf welches ich heruntergeladen und separat geöffnet hatte. (Nicht im Browser) (Vorschau Version 11.0 (999.4) Copyright 2002-2011, Apple Inc.)

**Comment by maltenorstroem** [comment]
Many thanks Marc for your input. The eBook has been updated.
